version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-web
    restart: always # Keep the container running or restart if it crashes
    ports:
      - "3002:3002"