services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-web
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
