apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
  labels:
    app: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: kubaivo/portfolio-app:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURE
              value: "false"
            # Pobieranie wartości z Secret:
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-app-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: portfolio-app-secrets
                  key: SMTP_PASS
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: portfolio-app-secrets
                  key: SMTP_FROM_EMAIL
            - name: CONTACT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: portfolio-app-secrets
                  key: CONTACT_EMAIL
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"